# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherITEA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'

  # Pods for WeatherITEA

  target 'WeatherITEATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherITEAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
